

requirements.txt: requirements.in
	@echo "Compile reqs"
	pip-compile $<

{{name}}.sif: {{name}}.def requirements.txt
	@echo "Compile image for {{name}}"
	sudo singularity build --notest {{name}}.sif {{name}}.def

all: {{name}}.sif

