

## The structure of the folders will be defined here by
## the path/name/panels

### HERE we define a figure (by starting a [[figures]] block)
[[figures]]
name = "figureXX_template"
path = "./main_figures"

### then we add panels to that figure with a panel sub-table
[[figures.panels]]
name = "f1_a"
path = "analysis/signatureAssigments/figures/id_profiles/groups_profiles/cfDNA_id_profile.pdf"

[[figures.panels]]
name = "f1_b"
path = "analysis/signatureAssigments/figures/id_profiles/groups_profiles/TCGA-PRAD_id_profile.pdf"

### WE can add a new figure folder as such

[[figures]]
name = "figureXX_template22"
path = "./supp_figures"

[[figures.panels]]
name = "f1_b"
path = "analysis/signatureAssigments/figures/id_profiles/groups_profiles/VALE-PD_id_profile.pdf"



