name: env2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ansible
  - numpy=1.22.0
  - tqdm=4.61.2
  - pip=22.0.3
  - pip:
    - beautifulsoup4==4.10.0
    - scikit-learn==1.0.2