
[data_pipeline]
nfprof = "sge,hpc,tower"
author = "DMP"
outdir = "results.nobackup"
figdir = "figures.nobackup"
tmpdir = "TMP.nobackup"
tabdir = "tables.nobackup"
## camelcase
name="dataMisc"

[data_simple]
author = "DMP"
## camelcase
name="dataMisc"

[singularity_py]
author = "DMP"
## camelcase
name="examplePy"
base_image="ubuntu:18.04"
version="0.0.1"
